cmsapp/urls.py
from django.urls import path
from .views import *
app_name = 'cmsapp'
_url_admin = 'cms-admin/'
urlpatterns = [


    path(_url_admin + "message/list/",
         AdminMessageListView.as_view(), name='adminmessagelist'),
    path(_url_admin + "<int:pk>/detail/",
         AdminMessageDetail.as_view(), name='adminmessagedetail'),


    path(_url_admin, AdminHomeView.as_view(), name='adminhome'),


    path('login/', LoginView.as_view(), name="login"),

    path('logout/', LogoutView.as_view(), name="logout"),

    path(_url_admin + "notice/list/",
         AdminNoticeListView.as_view(), name='adminnoticelist'),

    path(_url_admin + "notice/create/",
         AdminNoticeCreateView.as_view(), name='adminnoticecreate'),

    path(_url_admin + "notice/<int:pk>/delete/",
         AdminNoticeDeleteView.as_view(), name='adminnoticedelete'),

    path(_url_admin + "notice/<int:pk>/update/",
         AdminNoticeUpdateView.as_view(), name='adminnoticeupdate'),

    path(_url_admin + "event/list/",
         AdminEventListView.as_view(), name="admineventlist"),
    path(_url_admin + "event/create/",
         AdminEventCreateView.as_view(), name="admineventcreate"),
    path(_url_admin + "event/<int:pk>/update/",
         AdminEventUpdateView.as_view(), name="admineventupdate"),
    path(_url_admin + "event/<int:pk>/delete/",
         AdminEventDeleteView.as_view(), name="admineventdelete"),

    path(_url_admin + "blog/list/",
         AdminBlogListView.as_view(), name="adminbloglist"),
    path(_url_admin + "blog/create/",
         AdminBlogCreateView.as_view(), name="adminblogcreate"),
    path(_url_admin + "blog/<int:pk>/update/",
         AdminBlogUpdateView.as_view(), name="adminblogupdate"),
    path(_url_admin + "blog/<int:pk>/delete/",
         AdminBlogDeleteView.as_view(), name="adminblogdelete"),



    path(_url_admin + "gallery/list/",
         AdminGalleryListView.as_view(), name='admingallerylist'),
    path(_url_admin + "gallery/create/",
         AdminGalleryCreateView.as_view(), name='admingallerycreate'),
    path(_url_admin + "gallery/<int:pk>/update/",
         AdminGalleryUpdateView.as_view(), name='admingalleryupdate'),
    path(_url_admin + "gallery/<int:pk>/delete/",
         AdminGalleryDeleteView.as_view(), name='admingallerydelete'),

    path(_url_admin + "logo/list/",
         AdminLogoListView.as_view(), name='adminlogolist'),
    path(_url_admin + "logo/create/",
         AdminLogoCreateView.as_view(), name='adminlogocreate'),
    path(_url_admin + "logo/<int:pk>/update/",
         AdminLogoUpdateView.as_view(), name='adminlogoupdate'),
    path(_url_admin + "logo/<int:pk>/delete/",
         AdminLogoDeleteView.as_view(), name='adminlogodelete'),

    path(_url_admin + "aboutus/list/",
         AdminAboutusListView.as_view(), name='adminaboutuslist'),
    path(_url_admin + "aboutus/create/",
         AdminAboutusCreateView.as_view(), name='adminaboutuscreate'),
    path(_url_admin + "aboutus/<int:pk>/update/",
         AdminAboutusUpdateView.as_view(), name='adminaboutusupdate'),

    path(_url_admin + "newsevent/list/", AdminNewseventListView.as_view(), name='adminnewseventlist'),
    path(_url_admin + "newsevent/<int:pk>/detail/", AdminNewseventDetailView.as_view(), name='adminnewseventdetail'),    
    path(_url_admin + "newsevent/create/", AdminNewseventCreateView.as_view(), name='adminnewseventcreate'),
    path(_url_admin + "newsevent/<int:pk>/update/", AdminNewseventUpdateView.as_view(), name='adminnewseventupdate'),
    path(_url_admin + "newsevent/<int:pk>/delete/", AdminNewseventDeleteView.as_view(), name='adminnewseventdelete'),


    path(_url_admin + "projectarea/list/", AdminProjectAreaListView.as_view(), name='adminprojectarealist'),
    path(_url_admin + "projectarea/<int:pk>/detail/", AdminProjectAreaDetailView.as_view(), name='adminprojectareadetail'),    
    path(_url_admin + "projectarea/create/", AdminProjectAreaCreateView.as_view(), name='adminprojectareacreate'),
    path(_url_admin + "projectarea/<int:pk>/update/", AdminProjectAreaUpdateView.as_view(), name='adminprojectareaupdate'),
    path(_url_admin + "projectarea/<int:pk>/delete/", AdminProjectAreaDeleteView.as_view(), name='adminprojectareadelete'),


    path(_url_admin + "menubar/list/", AdminMenubarListView.as_view(), name='adminmenubarlist'),
    path(_url_admin + "menubar/<int:pk>/detail/", AdminMenubarDetailView.as_view(), name='adminmenubardetail'),    
    path(_url_admin + "menubar/create/", AdminMenubarCreateView.as_view(), name='adminmenubarcreate'),
    path(_url_admin + "menubar/<int:pk>/update/", AdminMenubarUpdateView.as_view(), name='adminmenubarupdate'),
    path(_url_admin + "menubar/<int:pk>/delete/", AdminMenubarDeleteView.as_view(), name='adminmenubardelete'),


    path(_url_admin + "slideshow/list/", AdminSlideShowListView.as_view(), name='adminslideshowlist'),
    path(_url_admin + "slideshow/create/", AdminSlideShowCreateView.as_view(), name='adminslideshowcreate'),
    path(_url_admin + "slideshow/<int:pk>/update/", AdminSlideShowUpdateView.as_view(), name='adminslideshowupdate'),
    path(_url_admin + "slideshow/<int:pk>/delete/", AdminSlideShowDeleteView.as_view(), name='adminslideshowdelete'),

    path(_url_admin + "overview/create/", AdminOverviewCreateView.as_view(), name="adminoverviewcreate"),
    path(_url_admin + "overview/list/", AdminOverviewListView.as_view(), name="adminoverviewlist",),
    path(_url_admin + "overview/<int:pk>/delete/", AdminOverviewDeleteView.as_view(), name="adminoverviewdelete"),
    path(_url_admin + "overview/<int:pk>/update/", AdminOverviewUpdateView.as_view(), name = "adminoverviewupdate"),

    path(_url_admin + "subscriber/list/", AdminSubscriberListView.as_view(), name = "adminsubscriberlist"),
    path(_url_admin + "subscriber/<int:pk>/delete/", AdminSubscriberDeleteView.as_view(), name = "adminsubscriberdelete"),
    #path(_url_admin + "subscriber/<int:pk>/detail/", AdminSubscriberDetailView.as_view(), name = "adminsubscriberdetail"),

    path(_url_admin + "personcat/create/", AdminPersonCatCreateView.as_view(), name="adminpersoncatcreate"),
    path(_url_admin + "personcat/list/", AdminPersonCatListView.as_view(), name="adminpersoncatlist",),
    path(_url_admin + "personcat/<int:pk>/delete/", AdminPersonCatDeleteView.as_view(), name="adminpersoncatdelete"),
    path(_url_admin + "personcat/<int:pk>/update/", AdminPersonCatUpdateView.as_view(), name = "adminpersoncatupdate"),

    path(_url_admin + "person/create/", AdminPersonCreateView.as_view(), name="adminpersoncreate"),
    path(_url_admin + "person/list/", AdminPersonListView.as_view(), name="adminpersonlist",),
    path(_url_admin + "person/<int:pk>/delete/", AdminPersonDeleteView.as_view(), name="adminpersondelete"),
    path(_url_admin + "person/<int:pk>/update/", AdminPersonUpdateView.as_view(), name = "adminpersonupdate"),

    path(_url_admin + "interested/create/", AdminInterestedCreateView.as_view(), name="admininterestedcreate"),
    path(_url_admin + "interested/list/", AdminInterestedListView.as_view(), name="admininterestedlist",),
    path(_url_admin + "interested/<int:pk>/delete/", AdminInterestedDeleteView.as_view(), name="admininteresteddelete"),
    path(_url_admin + "interested/<int:pk>/update/", AdminInterestedUpdateView.as_view(), name = "admininterestedupdate"),


    path(_url_admin + "sitesetting/create/", AdminSiteSettingCreateView.as_view(), name="adminsitesettingcreate"),
    path(_url_admin + "sitesetting/list/", AdminSiteSettingListView.as_view(), name="adminsitesettinglist",),
    path(_url_admin + "sitesetting/<int:pk>/delete/", AdminSiteSettingDeleteView.as_view(), name="adminsitesettingdelete"),
    path(_url_admin + "sitesetting/<int:pk>/update/", AdminSiteSettingUpdateView.as_view(), name = "adminsitesettingupdate"),
    path(_url_admin + "sitesetting/<int:pk>/updateU/", AdminSiteSettingUpdateUView.as_view(), name = "adminsitesettingupdateU"),

    path(_url_admin + "testimonial/create/", AdminTestimonialCreateView.as_view(), name="admintestimonialcreate"),
    path(_url_admin + "testimonial/list/", AdminTestimonialListView.as_view(), name="admintestimoniallist",),
    path(_url_admin + "testimonial/<int:pk>/delete/", AdminTestimonialDeleteView.as_view(), name="admintestimonialdelete"),
    path(_url_admin + "testimonial/<int:pk>/update/", AdminTestimonialUpdateView.as_view(), name = "admintestimonialupdate"),

    path(_url_admin + "reportcat/create/", AdminReportCatCreateView.as_view(), name="adminreportcatcreate"),
    path(_url_admin + "reportcat/list/", AdminReportCatListView.as_view(), name="adminreportcatlist",),
    path(_url_admin + "reportcat/<int:pk>/delete/", AdminReportCatDeleteView.as_view(), name="adminreportcatdelete"),
    path(_url_admin + "reportcat/<int:pk>/update/", AdminReportCatUpdateView.as_view(), name = "adminreportcatupdate"),

    path(_url_admin + "report/create/", AdminReportCreateView.as_view(), name="adminreportcreate"),
    path(_url_admin + "report/list/", AdminReportListView.as_view(), name="adminreportlist",),
    path(_url_admin + "report/<int:pk>/delete/", AdminReportDeleteView.as_view(), name="adminreportdelete"),
    path(_url_admin + "report/<int:pk>/update/", AdminReportUpdateView.as_view(), name = "adminreportupdate"),

    path(_url_admin + "settings/", AdminSettingsView.as_view(), name="adminsettingslist",),
    path(_url_admin + "idchecker/",IdCheckerView.as_view(), name="idchecker"),

    path(_url_admin + "registration/", AdminUserInfoRegView.as_view(), name="adminuserinfocreate"),
    path(_url_admin + "userinfo/<int:pk>/update/", AdminUserInfoUpdateView.as_view(), name="adminuserinfoupdate"),
    path(_url_admin + "userinfo/list/", AdminUserInfoListView.as_view(), name="adminuserinfolist"),
    path(_url_admin + "userinfo/<int:pk>/delete/", AdminUserInfoDeleteView.as_view(), name="adminuserinfodelete"),

cmsproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cmsapp.urls')),
    path('summernote/', include('django_summernote.urls')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admintemplates/adminblogdelete.html
{% extends 'admintemplates/base.html' %}

{% block content %}
<div class="bs-example2">
	<div class="modal-dialog">
		<div class="modal-content">
				<div class="modal-header">
					<a href="{% url 'cmsapp:adminbloglist' %}">
						<div class="close" data-dismiss="modal" aria-hidden="true">×</div>
					</a>
					<h2 class="modal-title">Delete Confirmation</h2>
				</div>				
				<div class="modal-body">
					<p>Are sure to delete '{{object.title}}'?</p>
				</div>
				<div class="modal-footer">
					<form method="POST" action="{% url 'cmsapp:adminblogdelete' object.id %}">	
	  					{% csrf_token %}
	  					<a href="{% url 'cmsapp:adminbloglist' %}" class="btn btn-default close" data-dismiss="modal">Cancel</a>
						<button class="btn btn-primary">Yes</button>
					</form>
				</div>
		</div>
	</div>
</div>
{% endblock %}

templates/admintemplates/adminbloglist.html
{% extends 'admintemplates/base.html' %}
{% load static %}

{% block content %}
<h3>Blogs </h3>
<h5 style="float: right;padding-right: 20px;">[<a href="{% url 'cmsapp:adminblogcreate' %}"> + Add New</a> ]     </h5>
<hr>
<table class="table table-hover"> 
	<thead>
		<tr>
			<th>S.N.</th>
			<th>Title</th>
			<th>Text</th>
			<th>Image</th>
			<th>Author</th>
			<th>Posted By</th>			
			<th width="8%">Action</th>
		</tr>
	</thead>
	<tbody>
		{% for blog in blogs %}
		<tr>
			<td>{{forloop.counter}}</td> 
			<td>{{blog.title}}</td>
			<td>{{blog.text|striptags|truncatewords:60|safe}}</td>
			<td><img src="{{blog.image.url}}" width="90"></td>
			<td>{{blog.author}}</td>
			<td>{{blog.created_by}}</td>			
			<td><a href="{% url 'cmsapp:adminblogdelete' blog.id %}"><i class="fa fa-trash-o"></i>  Delete</a><br>  
				<a href="{% url 'cmsapp:adminblogupdate' blog.id %}"><i class="fa fa-pencil-square-o"></i>  Edit</a></td>
		</tr>
		{% endfor %}
	</tbody>
	
</table>
{% endblock %}

templates/admintemplates/admineventdelete.html
{% extends 'admintemplates/base.html' %}

{% block content %}
<div class="bs-example2">
	<div class="modal-dialog">
		<div class="modal-content">
				<div class="modal-header">
					<a href="{% url 'cmsapp:admineventdelete' %}">
						<div class="close" data-dismiss="modal" aria-hidden="true">×</div>
					</a>
					<h2 class="modal-title">Delete Confirmation</h2>
				</div>				
				<div class="modal-body">
					<p>Are sure to delete '{{object.title}}'?</p>
				</div>
				<div class="modal-footer">
					<form method="POST" action="{% url 'cmsapp:admingallerydelete' object.id %}">	
	  					{% csrf_token %}
	  					<a href="{% url 'cmsapp:admineventdelete' %}" class="btn btn-default close" data-dismiss="modal">Cancel</a>
						<button class="btn btn-primary">Yes</button>
					</form>
				</div>
		</div>
	</div>
</div>
{% endblock %}

templates/admintemplates/admingallerylist.html
{% extends 'admintemplates/base.html' %}
{% load static %}

{% block content %}
  <link rel="stylesheet" href="{% static 'adminstatic/css/chocolat.css' %}" type='text/css' />
  <script src="{% static 'adminstatic/js/jquery.nicescroll.js' %}"></script>
  <script src="{% static 'adminstatic/js/jquery.chocrnizr.colat.js' %}"></script>
  <script src="{% static 'adminstatic/js/modeustom.04022.js' %}"></script>
  <script src="{% static 'adminstatic/js/jquery.chocolat.js' %}"></script>

  <script type="text/javascript">
    $(function() {
      $('.gallery-bottom a').Chocolat();
    });
    </script>
    <div class="outter-wp">
                <!--sub-heard-part-->
                   <div class="sub-heard-part">
                   <ol class="breadcrumb m-b-0">
                    <li><a href="/cms-admin/">Home</a></li>
                    <li class="active">Gallery</li>
                  </ol>
                   </div>
                  <!--//sub-heard-part-->
                <div class="graph-visual">
                    <h5 style="float: right;padding-right: 20px;">[<a href="{% url 'cmsapp:admingallerycreate' %}"> + Add New</a> ]     </h5>
                      <hr>
                      <h2 class="inner-tittle">Gallery </h2>
                           <!--/gallery-->
                           <div class="gallery">
                              <div class="gallery-bottom grid">
                                {% for gallery in galleries %}
                                <div class="col-md-3 g-left">
                                    <a href="{{gallery.image.url}}" rel="{{gallery.caption}} | <a href='/cms-admin/gallery/{{gallery.id}}/update/'><i class='fa fa-pencil-square-o'></i> Edit </a> | <a href='/cms-admin/gallery/{{gallery.id}}/delete/'><i class='fa fa-trash-o'></i>  Delete </a> " class="b-link-stripe b-animate-go  thickbox">
                                      <figure class="effect-oscar">
                                        <img src="{{gallery.image.url}}" alt=""/>
                                        <figcaption>
                                          <h4>{{gallery.title}}</h4>
                                            <p><i class="lnr lnr-magnifier"></i></p>
                                        </figcaption>     
                                      </figure>
                                    </a>
                                  </div>
                                  {% endfor %}
                                  <div class="clearfix"> </div>
                                </div>
                              </div>
                            </div>

                           <!--//gallery-->

                      </div>

{% endblock %}

templates/admintemplates/admininterestedcreate.html
{% extends 'admintemplates/base.html' %}

{% block content %}

<h3>Add Interested</h3>
<div class="maark-edit graph">
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.as_p}}
	<button class="btn btn-outline-primary">Submit</button>
	</form>
</div>

{% endblock %}

templates/admintemplates/admininterestedlist.html
{% extends 'admintemplates/base.html' %}
{% block content %}
	<h3>Interested List</h3>
		<div class="">
		<table class="table table-hover"> 
			<thead>
				<tr>   
					<th>S.N.</th>
					<th>Name</th>
					<th>Email</th>
					<th>Phone</th>
					<th>Amount</th>
					<th>Country</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				{% for interested in interesteds %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td>{{interested.name}}</td>
					<td>{{interested.email}}</td>
					<td>{{interested.phone}}</td>
					<td>{{interested.amount}}</td>
					<td>{{interested.country}}</td>
					<td><a href="{% url 'cmsapp:admininterestedupdate' interested.id %}"><i class="fa fa-pencil-square-o"></i>  Edit </a> |
						<a href="{% url 'cmsapp:admininteresteddelete' interested.id %}"><i class="fa fa-trash-o"></i> Delete</a> 
						</td>
				</tr>
				{% endfor %}
			</tbody>
			   
		</table>
	</div>
{% endblock %}

templates/admintemplates/adminmenubarlist.html
{% extends 'admintemplates/base.html' %}
{% block content %}
	<h3>Menubars</h3>
		<h5 style="float: right;padding-right: 20px;">[<a href="{% url 'cmsapp:adminmenubarcreate' %}"> + Add New</a> ]     </h5>
		<div class="">
		<table class="table table-hover"> 
			<thead>
				<tr>
					<th>S.N.</th>
					<th>Title</th>
					<th>Root</th>
					<th>Slug</th>
					<th>Priority</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				{% for menubar in menubars %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td><a href="{% url 'cmsapp:adminmenubardetail' menubar.id %}">
					{{menubar.title}}</a></td>
					<td>{{menubar.root}}</td>
					<td>{{menubar.slug}}</td>
					<td>{{menubar.priority}}</td>
					<td><a href="{% url 'cmsapp:adminmenubardetail' menubar.id %}"><i class="fa fa-trash-o"></i> Detail </a> | 
						<a href="{% url 'cmsapp:adminmenubarupdate' menubar.id %}"><i class="fa fa-pencil-square-o"></i>  Edit</a> 
						</td>
				</tr>
				{% endfor %}
			</tbody>
			   
		</table>
	</div>
{% endblock %}

templates/admintemplates/adminnoticedelete.html
{% extends 'admintemplates/base.html' %}

{% block content %}
<div class="bs-example2">
	<div class="modal-dialog">
		<div class="modal-content">
				<div class="modal-header">
					<a href="{% url 'cmsapp:adminnoticelist' %}">
						<div class="close" data-dismiss="modal" aria-hidden="true">×</div>
					</a>
					<h2 class="modal-title">Delete Confirmation</h2>
				</div>				
				<div class="modal-body">
					<p>Are sure to delete '{{object.title}}'?</p>
				</div>
				<div class="modal-footer">
					<form method="POST" action="{% url 'cmsapp:adminnoticedelete' object.id %}">	
	  					{% csrf_token %}
	  					<a href="{% url 'cmsapp:adminnoticelist' %}" class="btn btn-default close" data-dismiss="modal">Cancel</a>
						<button class="btn btn-primary">Yes</button>
					</form>
				</div>
		</div>
	</div>
</div>
{% endblock %}

templates/admintemplates/adminnoticelist.html
{% extends 'admintemplates/base.html' %}
{% load static %}

{% block content %}
<h3>Notice List</h3><hr>
<table class="table table-hover"> 
	<thead>
		<tr>
			<th>S.N.</th>
			<th>Title</th>
			<th>Date</th>
			<th>Crateed By</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		{% for notice in noticelist %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td>{{notice.title}}</td>
			<td>{{notice.date}}</td>
			<td>{{notice.created_by}}</td>
			<td><a href="{% url 'cmsapp:adminnoticedelete' notice.id %}"><i class="fa fa-trash-o"></i>  Delete</a> | 
				<a href="{% url 'cmsapp:adminnoticeupdate' notice.id %}"><i class="fa fa-pencil-square-o"></i>  Edit</a></td>
		</tr>
		{% endfor %}
	</tbody>
	
</table>
{% endblock %}

templates/admintemplates/adminpersoncatdelete.html
{% extends 'admintemplates/base.html' %}

{% block content %}
<div class="bs-example2">
	<div class="modal-dialog">
		<div class="modal-content">
				<div class="modal-header">
					<a href="{% url 'cmsapp:adminpersoncatlist' %}">
						<div class="close" data-dismiss="modal" aria-hidden="true">×</div>
					</a>
					<h2 class="modal-title">Delete Confirmation</h2>
				</div>				
				<div class="modal-body">
					<p>Are sure to delete '{{object.title}}'?</p>
				</div>
				<div class="modal-footer">
					<form method="POST" action="{% url 'cmsapp:adminpersoncatdelete' object.id %}">	
	  					{% csrf_token %}
	  					<a href="{% url 'cmsapp:adminpersoncatlist' %}" class="btn btn-default close" data-dismiss="modal">Cancel</a>
						<button class="btn btn-primary">Yes</button>
					</form>
				</div>
		</div>
	</div>
</div>
{% endblock %}

templates/admintemplates/adminpersoncatlist.html
{% extends 'admintemplates/base.html' %}
{% block content %}
	<h3>Teams Categories</h3>
		<h5 style="float: right;padding-right: 20px;">[<a href="{% url 'cmsapp:adminpersoncatcreate' %}"> + Add New</a> ]     </h5>
		<div class="">
		<table class="table table-hover"> 
			<thead>
				<tr>
					<th>S.N.</th>
					<th>Title</th>
					<th>Priority</th>	
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				{% for personcat in personcats %}
				<tr>
					<td>{{forloop.counter}}</td>
					<td>{{personcat.title}}</td>
					<td>{{personcat.priority}}</td>
					<td><a href="{% url 'cmsapp:adminpersoncatupdate' personcat.id %}">Update</a> |
						<a href="{% url 'cmsapp:adminpersoncatdelete' personcat.id %}">Delete</a> 
						</td>
				</tr>
				{% endfor %}
			</tbody>
			   
		</table>
	</div>
{% endblock %}

templates/admintemplates/adminpersondelete.html
{% extends 'admintemplates/base.html' %}

{% block content %}
<div class="bs-example2">
	<div class="modal-dialog">
		<div class="modal-content">
				<div class="modal-header">
					<a href="{% url 'cmsapp:adminpersonlist' %}">
						<div class="close" data-dismiss="modal" aria-hidden="true">×</div>
					</a>
					<h2 class="modal-title">Delete Confirmation</h2>
				</div>				
				<div class="modal-body">
					<p>Are sure to delete '{{object.name}}'?</p>
				</div>
				<div class="modal-footer">
					<form method="POST" action="{% url 'cmsapp:adminpersondelete' object.id %}">	
	  					{% csrf_token %}
	  					<a href="{% url 'cmsapp:adminpersonlist' %}" class="btn btn-default close" data-dismiss="modal">Cancel</a>
						<button class="btn btn-primary">Yes</button>
					</form>
				</div>
		</div>
	</div>
</div>
{% endblock %}

templates/admintemplates/adminsitesettingcreateU.html
{% extends 'admintemplates/base.html' %}

{% block content %}

<h3>Add Site Setting</h3>
<div class="maark-edit graph">
		<form class="form-horizontal" method="POST" enctype="multipart/form-data"> 
			{% csrf_token %}
			<div class="form-group">
				 <label for="inputEmail3" class="col-sm-2 control-label">Group</label> 
				 <div class="col-sm-9">
				 {{form.sitegroup}} 
				 </div>
			</div> 
			<div class="form-group">
				 <label for="inputEmail3" class="col-sm-2 control-label">Name</label> 
				 <div class="col-sm-9">
				 {{form.name}} 
				 </div>
			</div> 
			<div class="form-group">
				 <label for="inputEmail3" class="col-sm-2 control-label">Value</label> 
				 <div class="col-sm-9">
				 {{form.value}} 
				 </div>
			</div> 
			<div class="form-group"> 
				 <label for="inputEmail3" class="col-sm-2 control-label">Published</label> 
				 <div class="col-sm-9">
				 	{{form.published}}
				 </div>
			</div>

			<div class="col-sm-offset-2"> 
				<button class="btn btn-outline-primary">Submit</button>
			</div> 
		</form> 
</div>

{% endblock %}

templates/admintemplates/admintestimonialdelete.html
{% extends 'admintemplates/base.html' %}

{% block content %}
<div class="bs-example2">
	<div class="modal-dialog">
		<div class="modal-content">
				<div class="modal-header">
					<a href="{% url 'cmsapp:admintestimoniallist' %}">
						<div class="close" data-dismiss="modal" aria-hidden="true">×</div>
					</a>
					<h2 class="modal-title">Delete Confirmation</h2>
				</div>				
				<div class="modal-body">
					<p>Are sure to delete '{{object.name}}'?</p>
				</div>
				<div class="modal-footer">
					<form method="POST" action="{% url 'cmsapp:admintestimonialdelete' object.id %}">	
	  					{% csrf_token %}
	  					<a href="{% url 'cmsapp:admintestimoniallist' %}" class="btn btn-default close" data-dismiss="modal">Cancel</a>
						<button class="btn btn-primary">Yes</button>
					</form>
				</div>
		</div>
	</div>
</div>
{% endblock %}